CREATE USER PEGASO_PROD IDENTIFIED BY PEGASO1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO PEGASO_PROD;
GRANT CREATE TABLE TO PEGASO_PROD;
GRANT CREATE VIEW TO PEGASO_PROD;
GRANT CREATE SEQUENCE TO PEGASO_PROD;
GRANT CREATE TRIGGER TO PEGASO_PROD;
GRANT CREATE PROCEDURE TO PEGASO_PROD;
GRANT CREATE SYNONYM TO PEGASO_PROD;
GRANT CREATE TYPE TO PEGASO_PROD;

GRANT UNLIMITED TABLESPACE TO PEGASO_PROD;